#!/bin/bash

set -euo pipefail

if [[ $# != 1 ]]; then
    echo "Usage: " 1>&2
    echo "    $0 REMOTE_HOSTNAME" 1>&2
    exit 1
fi

REMOTE_HOSTNAME=$1

FORWARDED_SOCKET_DIR=~/.local/share/forwarded-agents-$REMOTE_HOSTNAME

CLIENT_GPG_SOCKET=$(gpgconf --list-dir agent-extra-socket)

# set up the remote gpg directory
mkdir -pm 700 $FORWARDED_SOCKET_DIR
ln -sf ${HOME}/.gnupg/pubring.kbx $FORWARDED_SOCKET_DIR/
ln -sf ${HOME}/.gnupg/trustdb.gpg $FORWARDED_SOCKET_DIR/

LOCAL_SSH_SOCK=${HOME}/.ssh/local_agent_sock

cat <<- EOF
# Example stanza to add to server's /etc/ssh/sshd_config:

# Allow binding over SSH/GPG agent sockets from old connections
Match User $USER
    StreamLocalBindUnlink yes

# Example of stanza to add to .profile on server
# (followed by a "source ~/.profile")

# Store the local ssh agent's socket so we can switch back to it if needed
if [ -z "\$SSH_CONNECTION" ] && [ -n "\$SSH_AUTH_SOCK" ]; then
    ln -fs "\${SSH_AUTH_SOCK}" $LOCAL_SSH_SOCK
fi
# Set up aliases for switching between local and remote gpg and ssh agents
alias use-agent-${REMOTE_HOSTNAME}="export GNUPGHOME=$FORWARDED_SOCKET_DIR SSH_AUTH_SOCK=$FORWARDED_SOCKET_DIR/ssh_socket"
alias use-agent-local="export GNUPGHOME=$HOME/.gnupg SSH_AUTH_SOCK=$LOCAL_SSH_SOCK"

# Example of stanza to add to .profile on client
# (followed by a "source ~/.profile")

# Store the local ssh agent's socket so we can switch back to it if needed
if [ -z "\$SSH_CONNECTION" ] && [ -n "\$SSH_AUTH_SOCK" ]; then
    ln -fs "\${SSH_AUTH_SOCK}" $LOCAL_SSH_SOCK
fi

# Example stanza to add to client's ~/.gnupg/gpg-agent.conf
# (then run "gpg-connect-agent reloadagent /bye")

extra-socket $CLIENT_GPG_SOCKET

# Example stanza to add to client's ssh config:
Host ${HOSTNAME}-dev
    Hostname $HOSTNAME
    ControlMaster auto
    ControlPath ~/.ssh/sockets/${HOSTNAME}-dev
    ControlPersist 15m
    RemoteForward ${FORWARDED_SOCKET_DIR}/ssh_socket $LOCAL_SSH_SOCK
    RemoteForward $(GNUPGHOME=$FORWARDED_SOCKET_DIR gpgconf --list-dirs agent-socket) $CLIENT_GPG_SOCKET
    ExitOnForwardFailure yes
    ForwardAgent no
EOF
