#!/bin/bash
set -euo pipefail

usage () {
    echo "Usage:" 1>&2
    echo "  $0 FORGE (user | group) NAME" 1>&2
    echo "" 1>&2
    echo "Examples:" 1>&2
    echo "  $0 github user todd" 1>&2
    echo "  $0 gitlab group riaa" 1>&2
    echo "  $0 gitlab:git.example.com group mib" 1>&2
    echo "  $0 forgejo:git2.example.com user falco" 1>&2
}

if ! [[ $# -eq 3 ]]; then
    usage
    exit 1
fi

# Parse forge
if [[ "$1" == 'github' ]]; then
    FORGE_TYPE=github
    FORGE_SITE=github.com
elif [[ "$1" == 'gitlab' ]]; then
    FORGE_TYPE=gitlab
    FORGE_SITE=gitlab.com
else
    FORGE_TYPE=$(echo "$1" | cut -d: -f1)
    FORGE_SITE=$(echo "$1" | cut -d: -f2)
fi

if [[ "$FORGE_TYPE" != "github" ]] \
        && [[ "$FORGE_TYPE" != "gitlab" ]] \
        && [[ "$FORGE_TYPE" != "forgejo" ]]; then
    echo "Error: unexpected forge type \"$FORGE_TYPE\"" 1>&2
    usage
    exit 1
fi

if [[ -z "$FORGE_SITE" ]]; then
    echo "Error: no forge site specified" 1>&2
    usage
    exit 1
fi

# Parse user or group
if [[ "$2" == "user" ]]; then
    IS_USER=true
elif [[ "$2" == "group" ]]; then
    IS_USER=false
else
    echo "Error: expected \"user\" or \"group\", but received \"$2\"" 1>&2
    usage
    exit 1
fi

# Parse name
NAME="$3"

# Basic setup
REPO_BASE_DIR="$(readlink -f .)/${FORGE_SITE}/${NAME}"
mkdir -p "$REPO_BASE_DIR"

pushd "$REPO_BASE_DIR" > /dev/null
CURRENT_REPO_SLUGS="$(ls -1 | xargs basename -s .git -a 2>/dev/null || true)"
popd > /dev/null

echo "Fetching repository list..."
LIST_REPOS=$(dirname $(readlink -f "$0"))/list-repos
REPO_URL_LIST=$($LIST_REPOS "$1" "$2" "$3")
REPO_SLUG_LIST=$(echo $REPO_URL_LIST | sed 's@\S*/\([^/ \t]*\).git@\1@g')

# Remove projects that were removed upstream
for slug in $CURRENT_REPO_SLUGS; do
    if !( echo $REPO_SLUG_LIST | grep -q $slug ); then
        echo removing project $slug that was not found upstream
        rm -rf "${REPO_BASE_DIR}/${slug}.git"
    fi
done

# Clone or update projects from upstream
for url in $REPO_URL_LIST; do
    slug=$(echo $url | sed 's@\S*/\([^/ \t]*\).git@\1@g')

    REPO_DIR="${REPO_BASE_DIR}/${slug}.git"
    if ! [[ -e "$REPO_DIR" ]]; then
        echo "Cloning $slug into ${REPO_DIR}"
        git clone --mirror "$url" "$REPO_DIR"
    else
        echo "Updating $slug in ${REPO_DIR}"
        git -C "$REPO_DIR" remote update --prune
    fi
done
